### ISSUE TITLE
[enhancement] Can Openetelemetry parse business code in user response body

### ISSUE THREAD

**Issue by oujinliang** [XiaoMi/ozhera#117]
For example, the returned business code has an error identifier, which you want to be reflected in metrics\trace\alert.

**Comment by sadadw1** [comment]
Now our practice is to let the business use Result in mone's infra-common, which will contain the code field, and if it starts with 5, we will consider the request an exception.
`
<dependency>
      <groupId>run.mone</groupId>
      <artifactId>infra-common</artifactId>
      <version>1.4-SNAPSHOT</version>
 </dependency>
`
