### ISSUE TITLE
Ozher hera-log supports multiple query storage

### ISSUE THREAD

**Issue by wtt40122** [XiaoMi/ozhera#133]
At present, Ozher hera log only supports elastic. For scalability, we almost support multiple types, such as Doris and Clickhouse, and support SQL queries

**Comment by goodjava** [comment]
We have discovered that Doris performs much better than ES in certain application scenarios, particularly in terms of query speed. Therefore, we are exploring the possibility of supporting additional storage engines.

**Comment by TreasureJade** [comment]
Has this feature been launched? If it has, does its performance meet expectations in actual use?

**Comment by wtt40122** [comment]
This feature has been fully developed, and Dorsi's big data writing is an extremely slow process. We have already supported batch writing of data, but we have also been improving the writing of big data
