### ISSUE TITLE
[enhancement] Looking forward to joining golang indicator monitoring

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#134]
Can Golang's services support indicator monitoring? For example, java services have jvm monitoring. Can golang's services support runtime monitoring?

**Comment by wtt40122** [comment]
Okay, I will be affected by the HTTP service in the hera app project that supports querying IP lists

**Comment by wodiwudi** [comment]
> Okay, I will be affected by the HTTP service in the hera app project that supports querying IP lists

we will implement it in the near future
