### ISSUE TITLE
About the alarm whitelist

### ISSUE THREAD

**Issue by glynnwei** [XiaoMi/ozhera#140]
When using the dingding alarm, we can not open too many permissions, we can only open the robot send message permissions, can there be a white list function, let us fill in the white list, and then the alarm if there is a white list directly go to the white list logic?

**Comment by wodiwudi** [comment]
#141  done! 
You can fill in the whitelist in hera.alert.whiteList of the nacos configuration prometheus_agent_open_config. Multiple whitelists are supported and separated by commas. The content is: ozhera user, userId.
When the alarm is triggered, the whitelist will be judged first. If hit, the content provided by the whitelist will be directly used as the user ID required for the alarm. Take the DingTalk whitelist as an example.
For example, configure a whitelist for two users: xxx and yyy: xxx@Gmail.com,123456,yyy@Gmail.com,654321
Later we will consider making the configuration page easier to operate.
