### ISSUE TITLE
[enhancement] Upgrade to JDK21

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#150]
Due to the significant advantages of JDK 21, we hope to upgrade all Ozhera projects to JDK 21. The following is the upgrade checklist, including the projects that need to be upgraded:

- [x] ozhera-app

- [x] ozhera-monitor

- [x] ozhera-demo-client

- [x] ozhera-demo-server

- [x] ozhera-log

- [x] ozhera-operator

- [x] ozhera-prometheus-agent

- [x] ozhera-tspandata

- [x] ozhera-webhook

- [x] prometheus-starter-all

- [x] trace-etl

**Comment by jifengzhilong** [comment]
done
