### ISSUE TITLE
[enhancement] The trace reporting span in Go supports log exporter

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#204]
The current reporting method in Golang relies on Jaeger as the backend for data collection. 

However, when there is high traffic, Jaeger may experience queue limitations. If the queue is full, excess spans will be discarded, which is sometimes unacceptable for troubleshooting. Additionally, communication between the business container and the Jaeger server involves gRPC, introducing potential network instability. 

Due to these limitations, similar to Java, we are introducing support for Golang log exporter. This approach involves outputting spans to log files and collecting/reporting them through a log agent. This method is considered more secure, stable, and reliable compared to Jaeger's reporting mechanism.

**Comment by wtt40122** [comment]
The log needs to support this and be able to obtain a list of service IPs
