### ISSUE TITLE
[enhancement] OzHera supports multiple data sources

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#222]
Due to the constraints of open-source licenses and in consideration of flexibility and scalability, we are contemplating adapting to and supporting multiple data sources.

1、We are considering switching the scenarios of reading and writing data in OzHera from Elasticsearch (ES) to Doris or ClickHouse. This requires us to make some changes:

Ideally, we should encapsulate the reading and writing of data sources into a common SDK. This way, the SDK can be used directly in the relevant places. The benefits of this approach include: 
  
1) no need to introduce unnecessary dependencies in the calling project.
2) minimal code modifications in the calling project.
    
All instances where ES is used need to be modified to call the encapsulated SDK. This includes:
    
1) ozhera-log
2) trace-etl
3) ozhera-mimonitor

2、We are also considering supporting various relational databases, not just MySQL, such as PostgreSQL. 
This may require us to modify all projects that use relational databases, including changes to POM files and configurations.

**Comment by sadadw1** [comment]
I checked the ozhera-operator, and it does not directly reference the ES pom dependency internally. If users need to use ES, the operator will make HTTP requests to ES to create the index templates required by ozhera. 

My idea is that, in the future, the operator will only need to adapt to Doris, creating the databases and tables needed by ozhera. We will support users in selecting data sources other than ES, such as Doris, on the operator page.

**Comment by wtt40122** [comment]
Currently, ozhera-log has already added support for Doris. We are building upon the modifications to ozhera-log to abstract ES and Doris into a common SDK, which will be made available for use in other projects such as trace-etl and ozhera-mimonitor.
The associated issue is: [Ozher hera-log supports multiple query storage · Issue #133 · XiaoMi/ozhera](https://github.com/XiaoMi/ozhera/issues/133)

**Comment by sadadw1** [comment]
The trace-etl project has been successfully refactored. #224
