### ISSUE TITLE
[enhancement] OzHer released the Release version

### ISSUE THREAD

**Issue by jifengzhilong** [XiaoMi/ozhera#255]
All projects of OzHera have been released in the Release version, and all project dependencies are also in the Release version. The projects currently awaiting modification are as follows:

- [x] ozhera-app
- [x] ozhera-demo-client
- [x] ozhera-demo-server
- [x] ozhera-log
- [x] ozhera-monitor
- [x] ozhera-operator
- [x] ozhera-prometheus-agent
- [x] ozhera-tspandata
- [x] ozhera-webhook
- [x] prometheus-starter-all
- [x] trace-etl

**Comment by sadadw1** [comment]
ozhera-app deploy release ref PR is #259

**Comment by wtt40122** [comment]
ozhera-app deploy release ref PR #266

**Comment by sadadw1** [comment]
ozhera-prometheus-agent deploy release ref PR #269
