### ISSUE TITLE
[bug]Error redirecting trace interface to log interface

### ISSUE THREAD

**Issue by TreasureJade** [XiaoMi/ozhera#305]
In Hera, I went further to the trace interface, but when I searched for relevant logs based on this traceID, there was no prompt for logs. However, in reality, I connected the logs
![img_v2_f7704a2c-13fa-4b3c-9d84-3c059debcb2l](https://github.com/XiaoMi/ozhera/assets/43409327/c9e9ea7d-6436-4f88-a42f-5868baa66058)

**Comment by wtt40122** [comment]
Yes, this is indeed a problem,
