### ISSUE TITLE
[enhancement] Optimizing SQL with OzHera Meta Data

### ISSUE THREAD

**Issue by jifengzhilong** [XiaoMi/ozhera#320]
Sometimes, paging can be very slow on certain databases. Our approach is to query for the maximum ID from the previous result, similar to executing SELECT * FROM table WHERE id > ? LIMIT ?. However, such SQL can result in no data being retrieved on some databases. Therefore, we add an ORDER BY clause to the SQL to ensure the order, modifying it to SELECT * FROM table WHERE id > ? ORDER BY id LIMIT ?.

**Comment by sadadw1** [comment]
resolve by #321
