### ISSUE TITLE
[bug] Can the system environment variables for protoc be configured?

### ISSUE THREAD

**Issue by jifengzhilong** [XiaoMi/ozhera#327]
The Maven compilation plugin used in hera-demo-client and hera-demo-server requires the version number of protoc to match the current operating system. However, in practice, we have found that many systems cannot read the ${os.detected.classifier} variable. I think we can set some variables in the pom.xml file, which can be used during compilation.

**Comment by sadadw1** [comment]
I think this is good idea!
