### ISSUE TITLE
We have always been lacking in terms of documentation. We plan to provide an official website, where we will present Ozhera's entire design concept and solutions to some problems encountered during development.

### ISSUE THREAD

**Issue by goodjava** [XiaoMi/ozhera#34]
We have always been lacking in terms of documentation. We plan to provide an official website, where we will present Ozhera's entire design concept and solutions to some problems encountered during development.

**Comment by renqingfu1** [comment]
We are currently working on the construction of our official website, and users can access it through https://ozhera.yling.top/zh/.

**Comment by sadadw1** [comment]
official website has been changed : https://ozhera.m.one.mi.com/
