### ISSUE TITLE
supporting ebpf ?

### ISSUE THREAD

**Issue by ad-vancing** [XiaoMi/ozhera#5]
I have reviewed your project and noted that it currently has a decent tracing capability. Have you considered supporting eBPF? As it generally requires no code modifications, it could be deemed less intrusive.

**Comment by rikaaa0928** [comment]
We are exploring ebpf for observability. Some experimental demos are being submitted to the [ebpf-preview](https://github.com/XiaoMi/ozhera/tree/ebpf-preview) branch. Welcome to participate in the development or provide more suggestions. By the way, could you please tell me in which specific aspects you would like ozhera to use ebpf?

**Comment by sadadw1** [comment]
Supporting eBPF is a great idea. One thing to note is: when using eBPF to link trace information, the parentSpanId of the eBPF's span should be obtained from the request chain (from the Http header). At the same time, the spanId of eBPF needs to be passed down (this might involve modifying the information in TCP packets). The presentation on OzHera should look like this:

![image](https://github.com/XiaoMi/ozhera/assets/128116675/869d07b8-8f0d-4a0c-b735-dc8154a7cb1a)
