### ISSUE TITLE
[enhancement] Ozhera's Plan for Extension Points in ETL Server and Log Agent

### ISSUE THREAD

**Issue by goodjava** [XiaoMi/ozhera#58]
Ozhera plans to extract extension points in the project, which will be convenient for the open-source community to expand. The advantage of extension points is that they are open for expansion while closed for modification. In the first phase, extension points will be added to the ETL server and Log Agent.

**Comment by goodjava** [comment]
The approach we can think of now is similar to Dubbo, having an extension project. When needed, it can be introduced into the project and then the configuration can be adjusted accordingly.

**Comment by HawickMason** [comment]
Will there be any protocols to follow if we want to utilize the upcoming extension points ~

**Comment by xiaotietietie** [comment]
just overview this project. it seems a very convenient tool for business systems monitoring and alerts!
btw, i am very interested in this project and want to be a contributor and also want to use this platform in the near future.
so i have a question to the person who is in charge of  this project, how can i become the contributor?
since kafka is also popular for both individuals and startup to use, i think maybe i  can apply kafka(another mq middleware) in this project first.
thanks!!

**Comment by shanwb** [comment]
> just overview this project. it seems a very convenient tool for business systems monitoring and alerts! btw, i am very interested in this project and want to be a contributor and also want to use this platform in the near future. so i have a question to the person who is in charge of this project, how can i become the contributor? since kafka is also popular for both individuals and startup to use, i think maybe i can apply kafka(another mq middleware) in this project first. thanks!!

Welcome, welcome, and your suggestions are excellent!

**Comment by shanwb** [comment]
![ozhera](https://github.com/XiaoMi/ozhera/assets/10281341/11770574-db5d-4f8f-8d71-bf4b04964686)
This is our WeChat community group, you can join the group for discussion.

**Comment by goodjava** [comment]
> just overview this project. it seems a very convenient tool for business systems monitoring and alerts! btw, i am very interested in this project and want to be a contributor and also want to use this platform in the near future. so i have a question to the person who is in charge of this project, how can i become the contributor? since kafka is also popular for both individuals and startup to use, i think maybe i can apply kafka(another mq middleware) in this project first. thanks!!

We will provide an extension point for MQ (and by default provide a RocketMQ implementation), you can refer to this.

**Comment by goodjava** [comment]
@xiaotietietie  This is a relatively early PR (https://github.com/XiaoMi/ozhera/pull/61), you can refer to it.

**Comment by sadadw1** [comment]
I will refer to this PR #61  to extend the RocketMQ Producer's extension.

**Comment by sadadw1** [comment]
> I will refer to this PR #61 to extend the RocketMQ Producer's extension.

I've added an extension for the RocketMQ Producer, which uses the same Extension as the Consumer. You can refer to this PR #71 .
