### ISSUE TITLE
[enhancement] opentelemetry-java-instrumentation sets the project environment-related information from the JVM to environment variables

### ISSUE THREAD

**Issue by oujinliang** [XiaoMi/ozhera#63]
opentelemetry-java-instrumentation sets the project environment-related information from the JVM to environment variables.

**Comment by sadadw1** [comment]
What's the purpose of doing this?

**Comment by sadadw1** [comment]
Some external users (some small companies) don't want to modify their existing Dockerfile to set the environment variables required by the probe. Instead, they hope to use JVM startup parameters as a substitute for environment variables.

**Comment by oujinliang** [comment]
Some external users (some small companies) don't want to modify their existing Dockerfile to set the environment variables required by the probe. Instead, they hope to use JVM startup parameters as a substitute for environment variables.

**Comment by sadadw1** [comment]
all right, I will do it.
