### ISSUE TITLE
Concerns about Log Transmission and ETL System's Impact on Metric Summarization and Prometheus Load

### ISSUE THREAD

**Issue by unlizhao** [XiaoMi/ozhera#7]
I've looked at your log transmission logic and the code for how your ETL system handles incoming information. I'm wondering if there's a scenario where each ETL server processes the incoming information, causing metrics to not summarize counter or histogram information well (since each set of ETL systems handles a portion), which puts more pressure on Prometheus. Do you have plans to modify this code? Or is this how the code is designed? My suggestion is that each ETL server only handles metrics information sent by a certain number of applications.

**Comment by sadadw1** [comment]
This is a good idea. Firstly, thank you for your idea. We have optimized the ETL service. Please see this document:
https://github.com/sadadw1/ozhera/blob/master/readme/optimization/metrics-optimization.md
