### ISSUE TITLE
[bug] The DingTalk alarm was effective only for a short period. After that, the log indicates an error with code: 400, "Invalid access_token request id: 5373616E-A1FB-750A-A30B-53495AC82560

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#74]
The DingTalk alarm was effective only for a short period. After that, the log indicates an error with code: 400, "Invalid access_token request id: 5373616E-A1FB-750A-A30B-53495AC82560.

**Comment by wodiwudi** [comment]
#78 done
