### ISSUE TITLE
[enhancement] Filter out the Redis GET command and retain spans with a duration exceeding 1s

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#76]
Previously, on the probe side, we filtered out spans for certain Redis commands, which proved to be highly effective. Now, we're considering filtering out the GET command and adding spans that exceed 1s. This way, the business will focus solely on anomalies and slow queries.

**Comment by oujinliang** [comment]
How much do we expect this change to reduce the number of spans?

**Comment by sadadw1** [comment]
This depends on the number of GET usages in the business application. However, based on experience, most business applications primarily use the GET command when working with Redis.
