### ISSUE TITLE
log-agent supported kafka exporter

### ISSUE THREAD

**Issue by wtt40122** [XiaoMi/ozhera#83]
currently, only Rocketmq exists, and we hope to support Kafka's

**Comment by wtt40122** [comment]
I have listed a document that can be used to implement an exporter that supports Kafka

https://github.com/wtt40122/docsAndImage/blob/main/Introduction%20to%20the%20log-agent-exporter%20Extension%20Point.pdf

**Comment by xiaotietietie** [comment]
hi
i try to implement this feature
pls check it
thanks
