### ISSUE TITLE
[enhancement] trace-etl add Kafka Extension

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#84]
`trace-etl` has completed its Extension overhaul, but currently, it only supports RocketMQ. Is it possible to add support for Kafka, taking reference from the RocketMQ implementation? The documentation for `trace-etl` Extension can be found at:

https://github.com/XiaoMi/ozhera/blob/master/trace-etl/docs/extension/extension.md

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by sadadw1** [comment]
Sorry for the late reply. If you'd like to contribute code for the Kafka extension of trace-etl, you can refer to this extension document for development. If you have any questions, feel free to discuss.
https://github.com/XiaoMi/ozhera/blob/master/trace-etl/docs/extension/extension.md
