### ISSUE TITLE
[bug] The pv storage of trace-etl-es has not been fully recycled.

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#86]
Trace-etl-es uses rocksDB as a local file cache. The file storage of rocksDB shows a cyclical and fluctuating growth. However, rocksDB has enabled TTL (Time-to-Live).

**Comment by oujinliang** [comment]
We have found the reason. It's because rocksDB has enabled dynamic compression, which leads to a significant increase in rocksDB logs. Moreover, there is no log clearance strategy, causing the pv storage space of rocksDB to be continuously occupied by log files.
