### ISSUE TITLE
Enhancing Log Agent Server with Multi-Instance Deployment Capability

### ISSUE THREAD

**Issue by goodjava** [XiaoMi/ozhera#91]
Currently, the log agent server is responsible for communication with all log agents (and maintaining heartbeats), but due to the underlying RPC mechanism, it is a single-point application. We will provide a PR to solve this problem, allowing the log agent server to be deployed in multiple instances.

**Comment by goodjava** [comment]
The modification of the basic library is here:https://github.com/XiaoMi/mone/issues/741

**Comment by wtt40122** [comment]
This is already very good, but it is best to support hashing to one of the machines based on specific values, whether it is a consumer or provider. I will try to support this later on
