### ISSUE TITLE
Use Java20 and Coroutines in Ozhera: A Caution Against Synchronized and a Recommendation for ReentrantLock

### ISSUE THREAD

**Issue by goodjava** [XiaoMi/ozhera#95]
At present, Java20 and coroutines are used in many places in Ozhera. Here, be careful with the use of synchronized, otherwise it can easily lead to threads being pinned. Try to use ReentrantLock in the code contributed. If you want to know more details, you can refer to a test case:https://github.com/XiaoMi/mone/issues/744

**Comment by wangmin9** [comment]
Yes, synchronized will cause virtual threads to be pinned, and we should try to avoid using it as much as possible
